In [ ]:
import requests
import lxml.html
from collections import defaultdict
import pandas as pd

## State Court Data Ingestion
Exploration of data sources for state courts for ingestion into Courts table. Working code now lives in ingest_courts_data.py.

Discussion: I think goal of functions in ingestion should be to produce an output which can be easily loaded into Django - not totally sure what the best format for that is, I think bulk create method takes a dict or we could go data -> pandas dataframe -> pandas to django convenience methods -> django. Should decide on a common output for ingestion functions.

### NCSC State Court Info
Scrape data on court selection methods, term lengths, etc for state courts from archived NCSC site: http://web.archive.org/web/20151022190427/http://www.judicialselection.us/judicial_selection/methods/selection_of_judges.cfm?state=

In [ ]:
# request and parse html
archive_ncsc_url = "http://web.archive.org/web/20151022190427/http://www.judicialselection.us/judicial_selection/methods/selection_of_judges.cfm?state="
r = requests.get(archive_ncsc_url)
response = lxml.html.fromstring(r.text)

In [ ]:
# parse html for state court info
state_data_dict = defaultdict(lambda: defaultdict(dict))
other_thing = []

for item in response.xpath('//div[@id="content"]/*'):
    if item.tag in ["h2", "h3", "p"]:
        continue
    # update the state
    elif item.tag == "div" and "yellow_box" in item.classes:
        state_str = item.xpath("h4/text()")[0]
    # get data for one state
    elif item.tag == "table":
        state_data_str = item.text_content()
        state_data_list = [
            item for item in state_data_str.replace("\t", "").split("\n") if item != ""
        ]
        stat_key = state_data_list[0]

        i = 1
        while i < len(state_data_list) - 1:
            court = state_data_list[i]
            stat_value = state_data_list[i + 1]
            state_data_dict[state_str][court][stat_key] = stat_value
            i += 2

state_data_dict

defaultdict(<function <lambda> at 0x0000027B1E16AFC0>, {'Alabama': defaultdict(<class 'dict'>, {'Supreme Court:': {'Number of Judgeships': '9', 'Number of Districts/Circuits': '--', 'Geographic Basis for Selection': 'statewide', 'Method of Selection (full term)': 'partisan election', 'Length of Term': '6 yrs', 'Method of Retention': 'reelection', 'Length of Subsequent Terms': '6 yrs', 'Method of Filling Interim Vacancies': 'gubernatorial appointment', 'When Interim Judges Stand for Election/Appointment': 'next general election after 1 yr in office', 'Selection of Chief Judge/Justice': 'popular election', 'Term of Office for Chief Judge/Justice': '6 yrs', 'Qualifications': 'licensed to practice law 10 yrs; 1 yr resident; maximum age of 70'}, 'Court of Criminal Appeals:': {'Number of Judgeships': '5', 'Number of Districts/Circuits': '--', 'Geographic Basis for Selection': 'statewide', 'Method of Selection (full term)': 'partisan election', 'Length of Term': '6 yrs', 'Method of Retention': 'reelection', 'Length of Subsequent Terms': '6 yrs', 'Method of Filling Interim Vacancies': 'gubernatorial appointment', 'When Interim Judges Stand for Election/Appointment': 'next general election after 1 yr in office', 'Selection of Chief Judge/Justice': 'peer vote', 'Term of Office for Chief Judge/Justice': 'indefinite', 'Qualifications': 'licensed to practice law 10 yrs; 1 yr resident; maximum age of 70'}, 'Court of Civil Appeals:': {'Number of Judgeships': '5', 'Number of Districts/Circuits': '--', 'Geographic Basis for Selection': 'statewide', 'Method of Selection (full term)': 'partisan election', 'Length of Term': '6 yrs', 'Method of Retention': 'reelection', 'Length of Subsequent Terms': '6 yrs', 'Method of Filling Interim Vacancies': 'gubernatorial appointment', 'When Interim Judges Stand for Election/Appointment': 'next general election after 1 yr in office', 'Selection of Chief Judge/Justice': 'seniority', 'Term of Office for Chief Judge/Justice': 'indefinite', 'Qualifications': 'licensed to practice law 10 yrs; 1 yr resident; maximum age of 70'}, 'Circuit Court:': {'Number of Judgeships': '144', 'Number of Districts/Circuits': '41', 'Geographic Basis for Selection': 'circuit', 'Method of Selection (full term)': 'partisan election', 'Length of Term': '6 yrs', 'Method of Retention': 'reelection', 'Length of Subsequent Terms': '6 yrs', 'Method of Filling Interim Vacancies': 'gubernatorial appointment*', 'When Interim Judges Stand for Election/Appointment': 'next general election after 1 yr in office', 'Selection of Chief Judge/Justice': 'peer vote', 'Term of Office for Chief Judge/Justice': '3 yrs', 'Qualifications': 'licensed to practice law 5 yrs; 1 yr resident of circuit; maximum age of 70'}}), 'Alaska': defaultdict(<class 'dict'>, {'Supreme Court:': {'Number of Judgeships': '5', 'Number of Districts/Circuits': '--', 'Geographic Basis for Selection': 'statewide', 'Method of Selection (full term)': 'gubernatorial appointment from nominating commission', 'Length of Term': 'at least 3 yrs', 'Method of Retention': 'retention election', 'Length of Subsequent Terms': '10 yrs', 'Method of Filling Interim Vacancies': 'gubernatorial appointment from nominating commission', 'When Interim Judges Stand for Election/Appointment': 'first general election more than 3 yrs after appointment', 'Selection of Chief Judge/Justice': 'peer vote', 'Term of Office for Chief Judge/Justice': '3 yrs', 'Qualifications': 'U.S. citizen; state resident 5 yrs; licensed to practice in state; 8 yrs active legal practice; mandatory retirement at 70'}, 'Court of Appeals:': {'Number of Judgeships': '3', 'Number of Districts/Circuits': '--', 'Geographic Basis for Selection': 'statewide', 'Method of Selection (full term)': 'gubernatorial appointment from nominating commission', 'Length of Term': 'at least 3 yrs', 'Method of Retention': 'retention election', 'Length of Subsequent Terms': '8 yrs', 'Method of Filling Interim Vacancies': 'gubernatorial appointment from nominating commission', 'When Interim Judges Stand for Election/Appointment': 'first general election more than 3 yrs after appointment', 'Selection of Chief Judge/Justice': 'chief justice appoints', 'Term of Office for Chief Judge/Justice': '2 yrs', 'Qualifications': 'U.S. citizen; state resident 5 yrs; licensed to practice in state; 8 yrs active legal practice; mandatory retirement at 70'}, 'Superior Court:': {'Number of Judgeships': '40', 'Number of Districts/Circuits': '4', 'Geographic Basis for Selection': 'district', 'Method of Selection (full term)': 'gubernatorial appointment from nominating commission', 'Length of Term': 'at least 3 yrs', 'Method of Retention': 'retention election', 'Length of Subsequent Terms': '6 yrs', 'Method of Filling Interim Vacancies': 'gubernatorial appointment from nominating commission', 'When Interim Judges Stand for Election/Appointment': 'first general election more than 3 yrs after appointment', 'Selection of Chief Judge/Justice': 'chief justice appoints', 'Term of Office for Chief Judge/Justice': '1 yr', 'Qualifications': 'U.S. citizen; state resident 5 yrs; licensed to practice in state; 5 yrs active legal practice; mandatory retirement at 70'}}), 'Arizona': defaultdict(<class 'dict'>, {'Supreme Court:': {'Number of Judgeships': '5', 'Number of Districts/Circuits': '--', 'Geographic Basis for Selection': 'statewide', 'Method of Selection (full term)': 'gubernatorial appointment from nominating commission', 'Length of Term': 'at least 2 yrs', 'Method of Retention': 'retention election', 'Length of Subsequent Terms': '6 yrs', 'Method of Filling Interim Vacancies': 'gubernatorial appointment from nominating commission', 'When Interim Judges Stand for Election/Appointment': 'next general election after 2 yrs in office', 'Selection of Chief Judge/Justice': 'peer vote', 'Term of Office for Chief Judge/Justice': '5 yrs', 'Qualifications': 'state resident and licensed in state 10 yrs; mandatory retirement at 70'}, 'Court of Appeals:': {'Number of Judgeships': '22', 'Number of Districts/Circuits': '2 divisions', 'Geographic Basis for Selection': 'division*', 'Method of Selection (full term)': 'gubernatorial appointment from nominating commission', 'Length of Term': 'at least 2 yrs', 'Method of Retention': 'retention election', 'Length of Subsequent Terms': '6 yrs', 'Method of Filling Interim Vacancies': 'gubernatorial appointment from nominating commission', 'When Interim Judges Stand for Election/Appointment': 'next general election after 2 yrs in office', 'Selection of Chief Judge/Justice': 'peer vote', 'Term of Office for Chief Judge/Justice': '1 yr', 'Qualifications': '30 yrs of age; state resident and licensed in state 5 yrs; local resident 1 yr; mandatory retirement at 70'}, 'Superior Court:': {'Number of Judgeships': '174', 'Number of Districts/Circuits': '15 counties', 'Geographic Basis for Selection': 'county', 'Method of Selection (full term)': 'partisan primary; nonpartisan general election/gubernatorial appointment from nominating commission**', 'Length of Term': '4 yrs/at least 2 yrs**', 'Method of Retention': 'reelection/retention election**', 'Length of Subsequent Terms': '4 yrs', 'Method of Filling Interim Vacancies': 'gubernatorial appointment/gubernatorial appointment from nominating commission**', 'When Interim Judges Stand for Election/Appointment': 'next general election/next general election after 2 yrs in office**', 'Selection of Chief Judge/Justice': 'supreme court appoints', 'Term of Office for Chief Judge/Justice': 'remainder of 4 yr term', 'Qualifications': '30 yrs of age; state resident and licensed in state 5 yrs; local resident 1 yr; mandatory retirement at 70'}}), 'Arkansas': defaultdict(<class 'dict'>, {'Supreme Court:': {'Number of Judgeships': '7', 'Number of Districts/Circuits': '1', 'Geographic Basis for Selection': 'statewide', 'Method of Selection (full term)': 'nonpartisan election*+', 'Length of Term': '8 yrs', 'Method of Retention': 'reelection', 'Length of Subsequent Terms': '8 yrs', 'Method of Filling Interim Vacancies': 'gubernatorial appointment', 'When Interim Judges Stand for Election/Appointment': 'next general election at least 4 mos after vacancy occurred', 'Selection of Chief Judge/Justice': 'popular election', 'Term of Office for Chief Judge/Justice': '8 yrs', 'Qualifications': '30 yrs of age; of good moral character; learned in the law; U.S. citizen; state resident > 2 yrs; 8 yrs practice of law'}, 'Court of Appeals:': {'Number of Judgeships': '12', 'Number of Districts/Circuits': '7', 'Geographic Basis for Selection': 'district', 'Method of Selection (full term)': 'nonpartisan election*+', 'Length of Term': '6 yrs', 'Method of Retention': 'reelection', 'Length of Subsequent Terms': '6 yrs', 'Method of Filling Interim Vacancies': 'gubernatorial appointment', 'When Interim Judges Stand for Election/Appointment': 'next general election at least 4 mos after vacancy occurred', 'Selection of Chief Judge/Justice': 'chief justice appoints', 'Term of Office for Chief Judge/Justice': '4 yrs', 'Qualifications': '30 yrs of age; of good moral charater; learned in the law; U.S. citizen; state resident > 2 yrs ; 8 yrs practice of law'}, 'Circuit Court:': {'Number of Judgeships': '122', 'Number of Districts/Circuits': '23', 'Geographic Basis for Selection': 'circuit', 'Method of Selection (full term)': 'nonpartisan election*+', 'Length of Term': '6 yrs', 'Method of Retention': 'reelection', 'Length of Subsequent Terms': '6 yrs', 'Method of Filling Interim Vacancies': 'gubernatorial appointment', 'When Interim Judges Stand for Election/Appointment': 'next general election at least 4 mos after vacancy occurred', 'Selection of Chief Judge/Justice': 'supreme court appoints', 'Term of Office for Chief Judge/Justice': 'no set term', 'Qualifications': '28 yrs of age; of good moral character; learned in the law; U.S. citizen; state resident > 2 yrs; 6 yrs practice of law'}}), 'California': defaultdict(<class 'dict'>, {'Supreme Court:': {'Number of Judgeships': '7', 'Number of Districts/Circuits': '--', 'Geographic Basis for Selection': 'statewide', 'Method of Selection (full term)': 'gubernatorial appointment;**confirmation by commission on judicial appointments***', 'Length of Term': '12 yrs', 'Method of Retention': 'retention election', 'Length of Subsequent Terms': '12 yrs', 'Method of Filling Interim Vacancies': 'gubernatorial appointment;**confirmation by commission on judicial appointments***', 'When Interim Judges Stand for Election/Appointment': 'next gubernatorial election', 'Selection of Chief Judge/Justice': 'gubernatorial appointment;**confirmation by commission on judicial appointments***', 'Term of Office for Chief Judge/Justice': '12 yrs', 'Qualifications': '10 yrs practice of law in state or service as judge of court of record'}, 'Court of Appeals:': {'Number of Judgeships': '102', 'Number of Districts/Circuits': '6', 'Geographic Basis for Selection': 'district', 'Method of Selection (full term)': 'gubernatorial appointment;**confirmation by commission on judicial appointments***', 'Length of Term': '12 yrs', 'Method of Retention': 'retention election', 'Length of Subsequent Terms': '12yrs', 'Method of Filling Interim Vacancies': 'gubernatorial appointment;**confirmation by commission on judicial appointments***', 'When Interim Judges Stand for Election/Appointment': 'next gubernatorial election', 'Selection of Chief Judge/Justice': 'gubernatorial appointment;**confirmation by commission on judicial appointments***', 'Term of Office for Chief Judge/Justice': '12 yrs', 'Qualifications': '10 yrs practice of law in state or service as judge of court of record'}, 'Superior Court:': {'Number of Judgeships': '1535', 'Number of Districts/Circuits': '58*', 'Geographic Basis for Selection': 'county', 'Method of Selection (full term)': 'nonpartisan election****+', 'Length of Term': '6 yrs', 'Method of Retention': 'reelection', 'Length of Subsequent Terms': '6 yrs', 'Method of Filling Interim Vacancies': 'gubernatorial appointment**', 'When Interim Judges Stand for Election/Appointment': 'next general election', 'Selection of Chief Judge/Justice': 'peer vote', 'Term of Office for Chief Judge/Justice': '1 or 2 yrs, depending on county', 'Qualifications': '10 yrs practice of law in state or service as judge of court of record'}}), 'Colorado': defaultdict(<class 'dict'>, {'Supreme Court:': {'Number of Judgeships': '7', 'Number of Districts/Circuits': '1', 'Geographic Basis for Selection': 'statewide', 'Method of Selection (full term)': 'gubernatorial appointment from nominating commission', 'Length of Term': 'at least 2 yrs', 'Method of Retention': 'retention election', 'Length of Subsequent Terms': '10 yrs', 'Method of Filling Interim Vacancies': 'gubernatorial appointment from nominating commission', 'When Interim Judges Stand for Election/Appointment': 'next general election after 2 yrs in office', 'Selection of Chief Judge/Justice': 'peer vote', 'Term of Office for Chief Judge/Justice': 'indefinite', 'Qualifications': 'qualified elector in state; licensed to practice law in state 5 yrs; mandatory retirement age of 72'}, 'Court of Appeals:': {'Number of Judgeships': '22', 'Number of Districts/Circuits': '1', 'Geographic Basis for Selection': 'statewide', 'Method of Selection (full term)': 'gubernatorial appointment from nominating commission', 'Length of Term': 'at least 2 yrs', 'Method of Retention': 'retention election', 'Length of Subsequent Terms': '8 yrs', 'Method of Filling Interim Vacancies': 'gubernatorial appointment form nominating commission', 'When Interim Judges Stand for Election/Appointment': 'next general election after 2 yrs in office', 'Selection of Chief Judge/Justice': 'chief justice appoints', 'Term of Office for Chief Judge/Justice': 'indefinite', 'Qualifications': 'qualified elector in state; licensed to practice law in state 5 yrs. mandatory retirement age of 72'}, 'District Court:': {'Number of Judgeships': '164', 'Number of Districts/Circuits': '22', 'Geographic Basis for Selection': 'county', 'Method of Selection (full term)': 'gubernatorial appointment from nominating commission', 'Length of Term': 'at least 2 yrs', 'Method of Retention': 'retention election', 'Length of Subsequent Terms': '6 yrs', 'Method of Filling Interim Vacancies': 'gubernatorial appointment from nominating commission', 'When Interim Judges Stand for Election/Appointment': 'next general election after 2 yrs in office', 'Selection of Chief Judge/Justice': 'chief justice appoints', 'Term of Office for Chief Judge/Justice': 'indefinite', 'Qualifications': 'qualified elector in district; licensed to practice law in state 5 yrs; mandatory retirment age of 72'}}), 'Connecticut': defaultdict(<class 'dict'>, {'Supreme Court:': {'Number of Judgeships': '7', 'Number of Districts/Circuits': '--', 'Geographic Basis for Selection': 'statewide', 'Method of Selection (full term)': 'gubernatorial nomination from judicial selection commission; legislative appointment', 'Length of Term': '8 yrs', 'Method of Retention': 'governor renominates; legislature reappoints', 'Length of Subsequent Terms': '8 yrs', 'Method of Filling Interim Vacancies': 'gubernatorial nomination from judicial selection commission; legislative appointment*', 'When Interim Judges Stand for Election/Appointment': '8 yrs', 'Selection of Chief Judge/Justice': 'gubernatorial nomination from judicial selection commission; legislative appointment*', 'Term of Office for Chief Judge/Justice': '8 yrs*', 'Qualifications': 'state resident; licensed to practice in state; mandatory retirement at 70'}, 'Appellate Court:': {'Number of Judgeships': '9', 'Number of Districts/Circuits': '--', 'Geographic Basis for Selection': 'statewide', 'Method of Selection (full term)': 'gubernatorial nomination from judicial selection commission; legislative appointment', 'Length of Term': '8 yrs', 'Method of Retention': 'governor renominates; legislature reappoints', 'Length of Subsequent Terms': '8 yrs', 'Method of Filling Interim Vacancies': 'gubernatorial nomination from judicial selection commission; legislative appointment', 'When Interim Judges Stand for Election/Appointment': '8 yrs', 'Selection of Chief Judge/Justice': 'chief justice', 'Term of Office for Chief Judge/Justice': 'N/A', 'Qualifications': 'state resident; licensed to practice in state; mandatory retirement at 70'}, 'Superior Court:': {'Number of Judgeships': '170', 'Number of Districts/Circuits': '--', 'Geographic Basis for Selection': 'statewide', 'Method of Selection (full term)': 'gubernatorial nomination from judicial selection commission; legislative appointment', 'Length of Term': '8 yrs', 'Method of Retention': 'governor renominates; legislature reappoints', 'Length of Subsequent Terms': '8 yrs', 'Method of Filling Interim Vacancies': 'gubernatorial nomination from judicial selection commission; legislative appointment', 'When Interim Judges Stand for Election/Appointment': '8 yrs', 'Selection of Chief Judge/Justice': 'chief court administrator', 'Term of Office for Chief Judge/Justice': 'at pleasure of chief court administrator', 'Qualifications': 'state resident; licensed to practice in state; mandatory retirement at 70'}}), 'Delaware': defaultdict(<class 'dict'>, {'Supreme Court:': {'Number of Judgeships': '5', 'Number of Districts/Circuits': '--', 'Geographic Basis for Selection': 'statewide', 'Method of Selection (full term)': 'gubernatorial appointment from judicial nominating commission with senate consent*', 'Length of Term': '12 yrs', 'Method of Retention': 'gubernatorial reappointment from judicial nominating commission with senate consent*', 'Length of Subsequent Terms': '12 yrs', 'Method of Filling Interim Vacancies': 'gubernatorial appointment from judicial nominating commission with senate consent*', 'When Interim Judges Stand for Election/Appointment': '12 yrs', 'Selection of Chief Judge/Justice': 'gubernatorial appointment from judicial nominating commission with senate consent*', 'Term of Office for Chief Judge/Justice': '12 yrs', 'Qualifications': 'state resident; "learned in the law"; state bar member'}, 'Superior Court:': {'Number of Judgeships': '20', 'Number of Districts/Circuits': '--', 'Geographic Basis for Selection': 'statewide', 'Method of Selection (full term)': 'gubernatorial appointment from judicial nominating commission with senate consent*', 'Length of Term': '12 yrs', 'Method of Retention': 'gubernatorial reappointment form judicial nominating commission with senate consent*', 'Length of Subsequent Terms': '12 yrs', 'Method of Filling Interim Vacancies': 'gubernatorial appointment from judicial nominating commission with senate consent*', 'When Interim Judges Stand for Election/Appointment': '12 yrs', 'Selection of Chief Judge/Justice': 'gubernatorial appointment from judicial nominating commission with senate consent*', 'Term of Office for Chief Judge/Justice': '12 yrs', 'Qualifications': 'state resident; law degree; "learned in the law"; state bar member'}, 'Court of Chancery:': {'Number of Judgeships': '1 Chancellor; 4 vice-chancellors', 'Number of Districts/Circuits': '--', 'Geographic Basis for Selection': 'statewide', 'Method of Selection (full term)': 'gubernatorial appointment from judicial nominating commission with senate consent*', 'Length of Term': '12 yrs', 'Method of Retention': 'gubernatorial reappointment from judicial nominating commission with senate consent*', 'Length of Subsequent Terms': '12 yrs', 'Method of Filling Interim Vacancies': 'gubernatorial appointment from judicial nominating commission with senate consent*', 'When Interim Judges Stand for Election/Appointment': '12 yrs', 'Selection of Chief Judge/Justice': 'gubernatorial appointment from judicial nominating commission with senate consent*', 'Term of Office for Chief Judge/Justice': '12 yrs', 'Qualifications': 'state resident; law degree; "learned in the law"; state bar member'}}), 'District of Columbia': defaultdi

In [ ]:
# variable names improved in real code
# reformat to flat dictionaries and convert to dataframe
things = []
for state, court_dict in state_data_dict.items():
    for court, info in court_dict.items():
        flat = {"State": state, "Court": court, **info}
        things.append(flat)
df = pd.DataFrame(things)
df

,State,Court,Number of Judgeships,Number of Districts/Circuits,Geographic Basis for Selection,Method of Selection (full term),Length of Term,Method of Retention,Length of Subsequent Terms,Method of Filling Interim Vacancies,When Interim Judges Stand for Election/Appointment,Selection of Chief Judge/Justice,Term of Office for Chief Judge/Justice,Qualifications
0,Alabama,Supreme Court:,9,--,statewide,partisan election,6 yrs,reelection,6 yrs,gubernatorial appointment,next general election after 1 yr in office,popular election,6 yrs,licensed to practice law 10 yrs; 1 yr resident...
1,Alabama,Court of Criminal Appeals:,5,--,statewide,partisan election,6 yrs,reelection,6 yrs,gubernatorial appointment,next general election after 1 yr in office,peer vote,indefinite,licensed to practice law 10 yrs; 1 yr resident...
2,Alabama,Court of Civil Appeals:,5,--,statewide,partisan election,6 yrs,reelection,6 yrs,gubernatorial appointment,next general election after 1 yr in office,seniority,indefinite,licensed to practice law 10 yrs; 1 yr resident...
3,Alabama,Circuit Court:,144,41,circuit,partisan election,6 yrs,reelection,6 yrs,gubernatorial appointment*,next general election after 1 yr in office,peer vote,3 yrs,licensed to practice law 5 yrs; 1 yr resident ...
4,Alaska,Supreme Court:,5,--,statewide,gubernatorial appointment from nominating comm...,at least 3 yrs,retention election,10 yrs,gubernatorial appointment from nominating comm...,first general election more than 3 yrs after a...,peer vote,3 yrs,U.S. citizen; state resident 5 yrs; licensed t...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
150,Wisconsin,Supreme Court:,7,--,statewide,nonpartisan election*,10 yrs,reelection,10 yrs,gubernatorial appointment**,next spring in which no other justice is to be...,seniority,indefinite,qualified elector of the state; licensed to pr...
151,Wisconsin,Court of Appeals:,16,4,district,nonpartisan election*,6 yrs,reelection,6 yrs,gubernatorial appointment**,next spring election in which no other judge f...,supreme court appoints,3 yrs,qualified elector of the state; licensed to pr...
152,Wisconsin,Circuit Court:,241,69,circuit,nonpartisan election*,6 yrs,reelection,6 yrs,gubernatorial appointment**,next spring election (if the vacancy occurs be...,supreme court appoints,2 yrs,qualified elector of circuit; licensed to prac...
153,Wyoming,Supreme Court:,5,--,statewide,gubernatorial appointment from nominating comm...,at least one year,retention election,8 yrs,gubernatorial appointment from nominating comm...,next general election 1 yr after appointment; ...,peer vote,4 yrs,U.S. citizen; state resident 3 yrs; 9 yrs lega...
154,Wyoming,District Court:,22,9,district,gubernatorial appointment from nominating comm...,at least 1 yr,retention election,6 yrs,gubernatorial appointment from nominating comm...,next general election 1 yr after appointment; ...,--,--,U.S. citizen; state resident 2 yrs; minimum ag...

In [77]:
selection_methods = (
    df["Method of Selection (full term)"].str.replace("*", "").str.replace("+", "").unique()
)
selection_methods

<StringArray>
[                                                                                      'partisan election',
                                                    'gubernatorial appointment from nominating commission',
     'partisan primary; nonpartisan general election/gubernatorial appointment from nominating commission',
                                                                                    'nonpartisan election',
                           'gubernatorial appointment;confirmation by commission on judicial appointments',
                    'gubernatorial nomination from judicial selection commission; legislative appointment',
                       'gubernatorial appointment from judicial nominating commission with senate consent',
                  'presidential appointment from judicial nomination commission, with senate confirmation',
                           'gubernatorial appointment from nominating commission with senate confirmation',
                                                 'gubernatorial appointment through nominating commission',
                                                      'gubernatorial appointment with senate confirmation',
   'gubernatorial appointment from nominating commission (17 districts); partisan election (14 districts)',
                        'gubernatorial appointment from nominating commission and/or nonpartisan election',
                                           'gubernatorial appointment with approval of governor's council',
                'gubernatorial appointment from nominating commission with approval of governor's council',
                                                               'partisan nomination; nonpartisan election',
 'gubernatorial nomination from selection commission recommendation; appointment by the executive council',
                                                                                                        '',
                                'gubernatorial appointment from nominating commission with senate consent',
     'chosen from among active and retired district judges, retired supreme court justices, and attorneys',
                                                          'partisan primary; nonpartisan general election',
                 'gubernatorial appointment from nominating commission with house and senate confirmation',
                                                                                    'legislative election']
Length: 23, dtype: str

### CourtListener
Get list of courts from CourtListener's dedicated courts API: https://www.courtlistener.com/api/rest/v4/courts/

API token required! Just need to sign in on CourtListener site and find token under developer tools.

In [ ]:
base_url = "https://www.courtlistener.com/"
courts_url = "api/rest/v4/courts/"
API_token = "REPLACE WITH YOUR API TOKEN"

In [13]:
courts_request = requests.get(
    base_url + courts_url, headers={"Authorization": f"Token {API_token}"}
)
courts_request.status_code

200

In [ ]:
courts_results = []
page_url = base_url + courts_url
while page_url is not None:
    r = requests.get(page_url, headers={"Authorization": f"Token {API_token}"})
    print(page_url, r.status_code)
    response = r.json()
    results = response["results"]
    courts_results.extend(results)
    page_url = response["next"]

In [ ]:
courtlistener_df = pd.DataFrame(courts_results)
courtlistener_df

Lots of the variables are kind of confusing; some jurisdictions mislabeled etc. Their state id decisions are crazy (Alabama is ala, Alaska is alaska, etc. wtf)

In [ ]:
# filter to jurisdiction "S" for statewide courts and non-NaN start date,
# NaN end date to get state supreme courts only.
cl_ssc_df = courtlistener_df[
    (courtlistener_df["jurisdiction"] == "S")
    & (courtlistener_df["start_date"].notna())
    & (courtlistener_df["end_date"].isna())
]
cl_ssc_df

,resource_uri,id,pacer_court_id,pacer_has_rss_feed,pacer_rss_entry_types,date_last_pacer_contact,fjc_court_id,date_modified,in_use,has_opinion_scraper,...,position,citation_string,short_name,full_name,url,start_date,end_date,jurisdiction,parent_court,appeals_to
393,https://www.courtlistener.com/api/rest/v4/cour...,ala,NaN,None,,None,,2023-01-06T11:30:36.039561-08:00,True,True,...,305.000,Ala.,Supreme Court of Alabama,Supreme Court of Alabama,http://judicial.alabama.gov/supreme.cfm,1819-01-01,NaN,S,NaN,[]
397,https://www.courtlistener.com/api/rest/v4/cour...,alaska,NaN,None,,None,,2013-08-14T09:46:30-07:00,True,True,...,320.000,Alaska,Alaska Supreme Court,Alaska Supreme Court,http://courts.alaska.gov/sp.htm,1959-01-03,NaN,S,NaN,[]
399,https://www.courtlistener.com/api/rest/v4/cour...,ariz,NaN,None,,None,,2013-08-14T09:46:30-07:00,True,True,...,322.000,Ariz.,Arizona Supreme Court,Arizona Supreme Court,http://www.azcourts.gov/azsupremecourt.aspx,1912-01-01,NaN,S,NaN,[]
403,https://www.courtlistener.com/api/rest/v4/cour...,ark,NaN,None,,None,,2013-09-08T18:32:48-07:00,True,True,...,330.000,Ark.,Supreme Court of Arkansas,Supreme Court of Arkansas,https://courts.arkansas.gov/courts/supreme-court,1841-01-01,NaN,S,NaN,[]
407,https://www.courtlistener.com/api/rest/v4/cour...,cal,NaN,None,,None,,2013-08-14T09:46:30-07:00,True,True,...,350.000,Cal.,California Supreme Court,California Supreme Court,http://www.courts.ca.gov/supremecourt.htm,1849-01-01,NaN,S,NaN,[]
571,https://www.courtlistener.com/api/rest/v4/cour...,colo,NaN,None,,None,,2014-07-11T13:49:42.750000-07:00,True,True,...,350.900,Colo.,Supreme Court of Colorado,Supreme Court of Colorado,http://www.coloradosupremecourt.com/,1876-08-01,NaN,S,NaN,[]
590,https://www.courtlistener.com/api/rest/v4/cour...,conn,NaN,None,,None,,2014-07-17T14:35:19.385000-07:00,True,True,...,351.500,Conn.,Supreme Court of Connecticut,Supreme Court of Connecticut,http://www.jud.state.ct.us/external/supapp/,1784-01-01,NaN,S,NaN,[]
594,https://www.courtlistener.com/api/rest/v4/cour...,del,NaN,None,,None,,2016-09-08T13:39:19.377323-07:00,True,True,...,352.000,Del.,Supreme Court of Delaware,Supreme Court of Delaware,http://courts.delaware.gov/supreme/,1832-01-01,NaN,S,NaN,[]
606,https://www.courtlistener.com/api/rest/v4/cour...,fla,NaN,None,,None,,2014-08-01T09:49:22.115000-07:00,True,True,...,354.000,Fla.,Supreme Court of Florida,Supreme Court of Florida,http://www.floridasupremecourt.org/,1845-01-01,NaN,S,NaN,[]
813,https://www.courtlistener.com/api/rest/v4/cour...,ga,NaN,None,,None,,2014-08-01T10:11:53.684000-07:00,True,True,...,355.500,Ga.,Supreme Court of Georgia,Supreme Court of Georgia,http://www.gasupreme.us/,1841-01-01,NaN,S,NaN,[]
857,https://www.courtlistener.com/api/rest/v4/cour...,haw,NaN,None,,None,,2013-08-14T09:46:30-07:00,True,True,...,359.000,Haw.,Hawaii Supreme Court,Hawaii Supreme Court,http://www.courts.state.hi.us/,1840-10-08,NaN,S,NaN,[]
859,https://www.courtlistener.com/api/rest/v4/cour...,idaho,NaN,None,,None,,2013-08-14T09:46:30-07:00,True,True,...,359.200,Idaho,Idaho Supreme Court,Idaho Supreme Court,http://www.isc.idaho.gov/,1863-01-01,NaN,S,NaN,[]
861,https://www.courtlistener.com/api/rest/v4/cour...,ill,NaN,None,,None,,2013-09-07T14:34:46-07:00,True,True,...,359.500,Ill.,Illinois Supreme Court,Illinois Supreme Court,http://www.state.il.us/court/,1841-01-01,NaN,S,NaN,[]
865,https://www.courtlistener.com/api/rest/v4/cour...,ind,NaN,None,,None,,2013-08-14T09:46:30-07:00,True,True,...,360.000,Ind.,Indiana Supreme Court,Indiana Supreme Court,http://www.in.gov/judiciary/supreme/,1816-01-01,NaN,S,NaN,[]
870,https://www.courtlistener.com/api/rest/v4/cour...,iowa,NaN,None,,None,,2014-08-01T11:44:06.700000-07:00,True,True,...,360.900,Iowa,Supreme Court of Iowa,Supreme Court of Iowa,http://www.iowacourts.gov/supreme_court/,1841-01-01,NaN,S,NaN,[]
872,https://www.courtlistener.com/api/rest/v4/cour...,kan,NaN,None,,None,,2014-08-01T12:03:19.219000-07:00,True,True,...,362.100,Kan.,Supreme Court of Kansas,Supreme Court of Kansas,http://www.kscourts.org/kansas-courts/supreme-...,1854-01-01,NaN,S,NaN,[]
875,https://www.courtlistener.com/api/rest/v4/cour...,ky,NaN,None,,None,,2014-08-08T10:26:58.771000-07:00,True,True,...,362.250,Ky.,Kentucky Supreme Court,Kentucky Supreme Court,http://courts.ky.gov/courts/supreme/‎,1976-01-01,NaN,S,NaN,[]
924,https://www.courtlistener.com/api/rest/v4/cour...,la,NaN,None,,None,,2014-07-17T07:08:09.249000-07:00,True,True,...,362.500,La.,Supreme Court of Louisiana,Supreme Court of Louisiana,http://www.lasc.org/,1813-01-01,NaN,S,NaN,[]
930,https://www.courtlistener.com/api/rest/v4/cour...,me,NaN,None,,None,,2025-02-26T10:01:21.453233-08:00,True,True,...,362.550,Me.,Supreme Judicial Court of Maine,Supreme Judicial Court of Maine,http://www.courts.state.me.us/maine_courts/sup...,1830-01-01,NaN,S,NaN,[]
932,https://www.courtlistener.com/api/rest/v4/cour...,md,NaN,None,,None,,2014-06-27T13:56:30.713000-07:00,True,True,...,362.600,Md.,Court of Appeals of Maryland,Court of Appeals of Maryland,http://www.courts.state.md.us/coappeals/,1841-01-01,NaN,S,NaN,[]
942,https://www.courtlistener.com/api/rest/v4/cour...,mass,NaN,None,,None,,2014-07-17T07:48:51.797000-07:00,True,True,...,362.990,Mass.,Massachusetts Supreme Judicial Court,Massachusetts Supreme Judicial Court,http://www.mass.gov/courts/sjc/,1692-01-01,NaN,S,NaN,[]
959,https://www.courtlistener.com/api/rest/v4/cour...,mich,NaN,None,,None,,2013-08-14T09:46:30-07:00,True,True,...,365.000,Mich.,Michigan Supreme Court,Michigan Supreme Court,http://courts.mi.gov/,1837-01-01,NaN,S,NaN,[]
1024,https://www.courtlistener.com/api/rest/v4/cour...,minn,NaN,None,,None,,2014-07-11T13:23:28.935000-07:00,True,True,...,365.200,Minn.,Supreme Court of Minnesota,Supreme Court of Minnesota,http://www.mncourts.gov/?page=550,1858-05-24,NaN,S,NaN,[]
1027,https://www.courtlistener.com/api/rest/v4/cour...,miss,NaN,None,,None,,2024-01-25T17:09:52.052109-08:00,True,True,...,366.000,Miss.,Mississippi Supreme Court,Mississippi Supreme Court,http://courts.ms.gov/appellate_courts/sc/sc.html,1841-01-01,NaN,S,NaN,[]
1030,https://www.courtlistener.com/api/rest/v4/cour...,mo,NaN,None,,None,,2024-01-25T17:10:18.802958-08:00,True,False,...,366.040,Mo.,Supreme Court of Missouri,Supreme Court of Missouri,http://www.courts.mo.gov/page.jsp?id=27,1821-01-01,NaN,S,NaN,[]
1036,https://www.courtlistener.com/api/rest/v4/cour...,mont,NaN,None,,None,,2013-08-14T09:46:30-07:00,True,True,...,366.100,Mont.,Montana Supreme Court,Montana Supreme Court,http://courts.mt.gov/supreme/default.mcpx,1864-01-01,NaN,S,NaN,[]
1039,https://www.courtlistener.com/api/rest/v4/cour...,neb,NaN,None,,None,,2019-08-23T21:10:38.352248-07:00,True,True,...,366.200,Neb.,Nebraska Supreme Court,Nebraska Supreme Court,http://supremecourt.ne.gov/,1854-01-01,NaN,S,NaN,[]
1042,https://www.courtlistener.com/api/rest/v4/cour...,nev,NaN,None,,None,,2013-08-14T09:46:30-07:00,True,True,...,366.500,Nev.,Nevada Supreme Court,Nevada Supreme Court,http://www.nevadajudiciary.us/index.php/suprem...,1864-01-01,NaN,S,NaN,[]
1044,https://www.courtlistener.com/api/rest/v4/cour...,nh,NaN,None,,None,,2014-07-02T13:37:51.009000-07:00,True,True,...,366.520,N.H.,Supreme Court of New Hampshire,Supreme Court of New Hampshire,http://www.courts.state.nh.us/supreme/,1776-01-01,NaN,S,NaN,[]
1048,https://www.courtlistener.com/api/rest/v4/cour...,nj,NaN,None,,None,,2013-09-08T18:34:43-07:00,True,True,...,366.550,N.J.,Supreme Court of New Jersey,Supreme Court of New Jersey,http://www.judiciary.state.nj.us/supreme/,1776-01-01,NaN,S,NaN,[]
1138,https://www.courtlistener.com/api/rest/v4/cour...,nm,NaN,None,,None,,2013-08-14T09:46:30-07:00,True,True,...,366.900,N.M.,New Mexico Supreme Court,New Mexico Supreme Court,https://nmsupremecourt.nmcourts.gov/index.php,1841-01-01,NaN,S,NaN,[]
1140,https://www.courtlistener.com/api/rest/v4/cour...,ny,NaN,None,,None,,2014-08-21T15:51:56.551000-07:00,True,True,...,366.960,NY,New York Court of Appeals,New York Court of Appeals,http://www.nycourts.gov/ctapps/,1777-01-01,NaN,S,NaN,[]
1632,https://www.courtlistener.com/api/rest/v4/cour...,nc,NaN,None,,None,,2016-09-08T13:38:41.131652-07:00,True,True,...,366.970,N.C.,Supreme Court of North Carolina,Supreme Court of North Carolina,http://www.nccourts.org/courts/appellate/supreme/,1799-01-01,NaN,S,NaN,[]
1637,https://www.courtlistener.com/api/rest/v4/cour...,nd,NaN,None,,None,,2013-08-14T09:46:30-07:00,True,True,...,366.990,N.D.,North Dakota Supreme Court,North Dakota Supreme Court,http://www.ndcourts.gov/default.htm,1861-01-01,NaN,S,NaN,[]
1640,https://www.courtlistener.com/api/rest/v4/cour...,ohio,NaN,None,,None,,2024-01-09T11:27:33.577135-08:00,True,True,...,366.995,Ohio,Ohio Supreme Court,Ohio Supreme Court,http://www.supremecourt.ohio.gov/,1841-01-01,NaN,S,NaN,[]
2125,https://www.courtlistener.com/api/rest/v4/cour...,okla,NaN,None,,None,,2016-09-08T13:40:27.897688-07:00,True,True,...,366.999,Okla.,Supreme Court of Oklahoma,Supreme Court of Oklahoma,http://www.oscn.net/oscn/schome/start.htm,1884-01-01,NaN,S,NaN,[]
2132,https://www.courtlistener.com/api/rest/v4/cour...,or,NaN,None,,None,,2013-08-14T09:46:30-07:00,True,True,...,367.000,Or.,Oregon Supreme Court,Oregon Supreme Court,http://www.publications.ojd.state.or.us/Pages/...,1841-01-01,NaN,S,NaN,[]
2162,https://www.courtlistener.com/api/rest/v4/cour...,pa,NaN,None,,None,,2014-08-01T13:56:27.532000-07:00,True,True,...,367.150,Pa.,Supreme Court of Pennsylvania,Supreme Court of Pennsylvania,http://www.pacourts.us/courts/supreme-court/,1722-05-22,NaN,S,NaN,[]
2426,https://www.courtlistener.com/api/rest/v4/cour...,ri,NaN,None,,None,,2014-08-08T13:59:44.315000-07:00,True,True,...,367.300,R.I.,Supreme Court of Rhode Island,Supreme Court of Rhode Island,http://www.courts.ri.gov/courts/supremecourt/d...,1747-01-01,NaN,S,NaN,[]
2429,https://www.courtlistener.com/api/rest/v4/cour...,sc,NaN,None,,None,,2013-09-08T23:22:31-07:00,True,True,...,367.400,S.C.,Supreme Court of South Carolina,Supreme Court of South Carolina,http://www.judicial.state.sc.us/supreme/,1841-01-01,NaN,S,NaN,[]
2434,https://www.courtlistener.com/api/rest/v4/cour...,sd,NaN,None,,None,,2013-08-14T09:46:30-07:00,True,True,...,367.500,S.D.,South Dakota Supreme Court,South Dakota Supreme Court,http://www.sdjudicial.com/,1889-01-01,NaN,S,NaN,[]
2435,https://www.courtlistener.com/api/rest/v4/cour...,tenn,NaN,None,,None,,2016-09-08T13:39:03.982890-07:00,True,True,...,367.600,Tenn.,Tennessee Supreme Court,Tennessee Supreme Court,https://www.tncourts.gov/courts/supreme-court,1790-01-01,NaN,S,NaN,[]
2441,https://www.courtlistener.com/api/rest/v4/cour...,tex,NaN,None,,None,,2014-08-08T10:27:09.820000-07:00,True,True,...,368.000,Tex.,Texas Supreme Court,Texas Supreme Court,http://www.supreme.courts.state.tx.us/,1840-01-01,NaN,S,NaN,[]
3144,https://www.courtlistener.com/api/rest/v4/cour...,utah,NaN,None,,None,,2013-08-14T09:46:30-07:00,True,True,...,369.000,Utah,Utah Supreme Court,Utah Supreme Court,http://www.utcourts.gov/opinions/supopin/index...,1850-01-01,NaN,S,NaN,[]
3147,https://www.courtlistener.com/api/rest/v4/cour...,vt,NaN,None,,None,,2013-09-09T10:24:51-07:00,True,True,...,369.200,Vt.,Supreme Court of Vermont,Supreme Court of Vermont,http://www.vermontjudiciary.org/gtc/supreme/de...,1778-01-01,NaN,S,NaN,[]
3149,https://www.courtlistener.com/api/rest/v4/cour...,va,NaN,None,,None,,2013-09-09T10:23:22-07:00,True,True,...,369.400,Va.,Supreme Court of Virginia,Supreme Court of Virginia,http://www.courts.state.va.us/courts/scv/,1779-01-01,NaN,S,NaN,[]
3273,https://www.courtlistener.com/api/rest/v4/cour...,wash,NaN,None,,None,,2024-11-18T10:43:44.145801-08:00,True,True,...,370.000,Wash.,Washington Supreme Court,Washington Supreme Court,https://www.courts.wa.gov/appellate_trial_cour...,1889-01-01,NaN,S,NaN,[]
3277,https://www.courtlistener.com/api/rest/v4/cour...,wva,NaN,None,,None,,2013-08-14T09:46:30-07:00,True,True,...,385.100,W. Va.,West Virginia Supreme Court,West Virginia Supreme Court,http://www.courtswv.gov/supreme-court/,1863-01-01,NaN,S,NaN,[]
3280,https://www.courtlistener.com/api/rest/v4/cour...,wis,NaN,None,,None,,2013-08-14T09:46:30-07:00,True,True,...,386.000,Wis.,Wisconsin Supreme Court,Wisconsin Supreme Court,http://www.wicourts.gov/courts/supreme/index.htm,1836-01-01,NaN,S,NaN,[]
3283,https://www.courtlistener.com/api/rest/v4/cour...,wyo,NaN,None,,None,,2013-08-14T09:46:30-07:00,True,True,...,390.000,Wyo.,Wyoming Supreme Court,Wyoming Supreme Court,http://www.courts.state.wy.us/,1921-01-01,NaN,S,NaN,[]

In [ ]:
# save to csv file
# courtlistener_df.to_csv("courts_courtlistener.csv")