In [ ]:
import requests
import lxml.html
from pypdf import PdfReader
import pandas as pd
from google import genai
from pathlib import Path
from google.genai import types
import os
import us
from datetime import datetime

from dotenv import load_dotenv, find_dotenv
from pydantic import BaseModel, Field
from typing import List, Optional

from ingest_sc_cases import case_df
from ingest_sc_judges import judge_pd

Scraped judge: Abigail LeGrow
Scraped judge: Adam Tanenbaum
Scraped judge: Aimee A. Oravec
Scraped judge: Alisa Kelli Wise
Scraped judge: Allison Riggs
Scraped judge: Andrew J. McDonald
Scraped judge: Andrew M. Horton
Scraped judge: Andrew M. Mead
Scraped judge: Andrew Pinson
Scraped judge: Angela M. Eaves
Scraped judge: Angela McCormick Bisig
Scraped judge: Anita Earls
Scraped judge: Ann A. Scott Timmer
Scraped judge: Anna Blackburne-Rigsby
Scraped judge: Anne K. McKeig
Scraped judge: Anne M. Patterson
Scraped judge: Annette Kingsland
  Ziegler
Scraped judge: Anthony Cannataro
Scraped judge: Aruna Masih
Scraped judge: Barbara A. Madsen
Scraped judge: Barbara Webb
Scraped judge: Benjamin A. Land
Scraped judge: Bert Richardson
Scraped judge: Beth Baker
Scraped judge: Brady E. Mendheim, Jr.
Scraped judge: Brett Busby
Scraped judge: Brian D. Boatright
Scraped judge: Brian Hagedorn
Scraped judge: Brian K. Zahra
Scraped judge: Briana Zamora
Scraped judge: Bronson James
Scraped judge: Bryan K. Gould
Scraped judge: Brynja M. Booth
Scraped judge: C. Shannon Bacon
Scraped judge: Cade Cole
Scraped judge: Caitlin Halligan
Scraped judge: Caleb Stegall
Scraped judge: Carla Wong McMillian
Scraped judge: Carlos A. Samour, Jr.
Scraped judge: Carlos G. Muñiz
Scraped judge: Carol A. Corrigan
Scraped judge: Catharine F. Easterly
Scraped judge: Catherine R. Connors
Scraped judge: Charles J. Bethel
Scraped judge: Charles Trump
Scraped judge: Charles W. Johnson
Scraped judge: Chris Garrett
Scraped judge: Chris McCool
Scraped judge: Christina Nolan
Scraped judge: Christine Donohue
Scraped judge: Christopher M Goff
Scraped judge: Christopher McDonald
Scraped judge: Christopher Shea Nickell
Scraped judge: Cleo E. Powell
Scraped judge: Clint Bolick
Scraped judge: Colleen D. Zahn
Scraped judge: Colleen Melody
Scraped judge: Collins J. Seitz, Jr.
Scraped judge: Corinne A. Beckwith
Scraped judge: Cory Swanson
Scraped judge: Courtney Rae Hudson
Scraped judge: Cynthia Meyer
Scraped judge: D. Arthur Kelsey
Scraped judge: D. Garrison Hill
Scraped judge: Dalila Argaez Wendlandt
Scraped judge: Dan Biles
Scraped judge: Dan Hawkins
Scraped judge: Dana Kuehn
Scraped judge: Dana Oxley
Scraped judge: Daniel E. Will
Scraped judge: Daniel J. Crothers
Scraped judge: Daniel McCaffery
Scraped judge: Dario Borghesan
Scraped judge: David K. Overstreet
Scraped judge: David K. Thomson
Scraped judge: David Lewis
Scraped judge: David M. Ishee
Scraped judge: David N. May
Scraped judge: David N. Wecht
Scraped judge: David Newell
Scraped judge: David Schneck
Scraped judge: David Sullivan
Scraped judge: Debra Hembree Lambert
Scraped judge: Debra L. Stephens
Scraped judge: Debra Lehrmann
Scraped judge: Debra Todd
Scraped judge: Derek Molter
Scraped judge: Derek Vaughn
Scraped judge: Diana Hagen*
Scraped judge: Douglas Bahr
Scraped judge: Douglas Fasciale
Scraped judge: Douglas Herndon
Scraped judge: Douglas L. Combs
Scraped judge: Dustin P. Rowe
Scraped judge: Dwight Tarwater
Scraped judge: Edward M. Mansfield
Scraped judge: Elissa F. Cadish
Scraped judge: Elizabeth “Bessie” Dewar
Scraped judge: Elizabeth M. Welch
Scraped judge: Elizabeth Rochford
Scraped judge: Elizabeth T. Clement
Scraped judge: Eric S. Rosen
Scraped judge: Erin Lynch Prata
Scraped judge: Evan Young
Scraped judge: Fabiana Pierre-Louis
Scraped judge: Frank M. Gaziano
Scraped judge: G. Helen Whitener
Scraped judge: G. Richard Bevan
Scraped judge: Gabrielle Wolohojian
Scraped judge: Gary F. Traynor
Scraped judge: Gary Lumpkin
Scraped judge: Geoffrey G Slaughter
Scraped judge: George C. James, Jr.
Scraped judge: Gerald Titus
Scraped judge: Gina Parker
Scraped judge: Ginger Gooch
Scraped judge: Goodwin H. Liu
Scraped judge: Gordon J. MacDonald
Scraped judge: Gordon Moore
Scraped judge: Greg Cook
Scraped judge: Greg Shaw
Scraped judge: Gregory T. D’Auria
Scraped judge: Gregory W. Moeller
Scraped judge: Haley Bunn
Scraped judge: Harold E. Eaton, Jr.
Scraped judge: Holly Kirby
Scraped judge: Ingrid Gustafson
Scraped judge: J. Cody Hiland
Scraped judge: James A. Rice
Scraped judge: James D. Maxwell II
Scraped judge: James E. Edmondson
Scraped judge: James Jeremiah Shea
Scraped judge: James P. Beene
Scraped judge: James P. Sullivan
Scraped judge: James R. Winchester
Scraped judge: Jamie R. Grosshans
Scraped judge: Jane Bland
Scraped judge: Janet Protasiewicz
Scraped judge: Jason M. Bergevin
Scraped judge: Jay B. McCallum
Scraped judge: Jefferson D. Hughes III
Scraped judge: Jeffrey J. Funke
Scraped judge: Jeffrey S. Bivins
Scraped judge: Jenifer Branning
Scraped judge: Jennifer Brunner
Scraped judge: Jennifer S. Henderson
Scraped judge: Jenny Rivera
Scraped judge: Jerod Tufte
Scraped judge: Jesse F McClure, III
Scraped judge: Jill J. Karofsky
Scraped judge: Jill Pohlman
Scraped judge: Jimmy Blacklock
Scraped judge: John Cannon Few
Scraped judge: John D. Couriel
Scraped judge: John G. Fenn
Scraped judge: John Guidry
Scraped judge: John J. Ellington
Scraped judge: John Jay Hoffman
Scraped judge: John L. Weimer
Scraped judge: John Nielsen
Scraped judge: John P. Howard III
Scraped judge: John Phillip Devine
Scraped judge: John R. Freudenberg
Scraped judge: John R. Lopez IV
Scraped judge: John W. Kittredge
Scraped judge: Jon J. Jensen
Scraped judge: Jonathan Biran
Scraped judge: Jonathan J. Papik
Scraped judge: Jorge Labarga
Scraped judge: Joseph Deters
Scraped judge: Joshua Deahl
Scraped judge: Joshua P. Groban
Scraped judge: Josiah Dennis Coleman
Scraped judge: Joy V. Cunningham
Scraped judge: Jude Pate
Scraped judge: Julia M. Lipez
Scraped judge: Julie J. Vargas
Scraped judge: Junius P. Fulton III
Scraped judge: Karen L. Valihura
Scraped judge: Karen R. Baker
Scraped judge: Kari Gray
Scraped judge: Karl Procaccini
Scraped judge: Kate M. Fox
Scraped judge: Katherine Biidegaray
Scraped judge: Kathryn H. King
Scraped judge: Kelli Evans
Scraped judge: Kelly C. Broniec
Scraped judge: Kelly Thompson
Scraped judge: Kenny Griffis
Scraped judge: Kevin Brobson
Scraped judge: Kevin M. Dougherty
Scraped judge: Kevin Patrick Yeary
Scraped judge: Keynen “KJ” Wall Jr.
Scraped judge: Kimberly Ann Thomas
Scraped judge: Kimberly S. Budd
Scraped judge: Kristina Pickering
Scraped judge: Kyle D. Hawkins
Scraped judge: Kyra Harris Bolden
Scraped judge: Larkin Walsh
Scraped judge: Laurie McKinnon
Scraped judge: Lee Finley “Gary”
Scraped judge: Leondra R. Kruger
Scraped judge: Leslie D. King
Scraped judge: Letitia Verdin
Scraped judge: Lidia S. Stiglich
Scraped judge: Linda M. Bell
Scraped judge: Lisa Fair McEvers
Scraped judge: Lisa Ginoza
Scraped judge: Lisa Holder White
Scraped judge: Loretta H. Rush
Scraped judge: Lynne Boomgaarden
Scraped judge: M. John Kane, IV
Scraped judge: Madeline Singas
Scraped judge: Maria E. Berkenkotter
Scraped judge: Maria Elena Cruz
Scraped judge: Mark E. Salter
Scraped judge: Mark S Massa
Scraped judge: Marla Luckert
Scraped judge: Mary Kay O’Brien
Scraped judge: Mary L. Wagner
Scraped judge: Mary Lou Keel
Scraped judge: Mary R. Russell
Scraped judge: Matthew B. Durrant
Scraped judge: Matthew Fader
Scraped judge: Matthew McDermott
Scraped judge: Maureen McKenna Goldberg
Scraped judge: Meagan Aileen Flynn
Scraped judge: Megan K. Cavanagh
Scraped judge: Megan Shanahan
Scraped judge: Melissa A. Long
Scraped judge: Melissa Beth Countway
Scraped judge: Melissa Taylor Standridge
Scraped judge: Meredith Sasso
Scraped judge: Michael E. Vigil
Scraped judge: Michael J. Garcia
Scraped judge: Michael K. Randolph
Scraped judge: Michael Noriega
Scraped judge: Michael P. Drescher
Scraped judge: Michelle M. Keller
Scraped judge: Monica M. Márquez
Scraped judge: N. Christopher Griffiths
Scraped judge: Nancy Waples
Scraped judge: Natalie E. Hudson
Scraped judge: Nels S.D. Peterson
Scraped judge: Noma Diane Gurich
Scraped judge: Nora Dannehy
Scraped judge: P. Scott Neville, Jr.
Scraped judge: Paige Petersen
Scraped judge: Pamela R. Goodwine
Scraped judge: Patricia Guerrero
Scraped judge: Patricia J. DeVaney
Scraped judge: Patricia Lee
Scraped judge: Patrick E. Donovan
Scraped judge: Patrick F. Fischer
Scraped judge: Paul A. Suttell
Scraped judge: Paul C. Thissen
Scraped judge: Paul C. Wilson
Scraped judge: Paul L. Reiber
Scraped judge: Paul Newby
Scraped judge: Peter K. Killough
Scraped judge: Philip Berger Jr.
Scraped judge: Piper D. Griffin
Scraped judge: R. Patrick DeWine
Scraped judge: Rachel Wainer-Apter
Scraped judge: Raheem L. Mullins
Scraped judge: Raquel Montoya-Lewis
Scraped judge: Rebeca Aizpuru Huddle
Scraped judge: Rebecca Duncan
Scraped judge: Rebecca Frank Dallet
Scraped judge: Rebecca Grassl Bradley
Scraped judge: Renatha Francis
Scraped judge: Rhonda K. Wood
Scraped judge: Richard Bernstein
Scraped judge: Richard Darby
Scraped judge: Richard Dietz
Scraped judge: Richard L. Gabriel
Scraped judge: Rick Lawrence
Scraped judge: Robert B. Conley
Scraped judge: Robert Gusinsky
Scraped judge: Robert Hudson
Scraped judge: Robert Jarosh
Scraped judge: Robert P. Chamberlin
Scraped judge: Robin Ransom
Scraped judge: Robyn M. Brody
Scraped judge: Roger DeHoog
Scraped judge: Ron D. Parraguirre
Scraped judge: Rowan D. Wilson
Scraped judge: Roy W. McLeese
Scraped judge: Sabrina S. McKenna
Scraped judge: Sal Mungia
Scraped judge: Sallie Updyke Mundy
Scraped judge: Sanjay T. Tailor
Scraped judge: Sarah H. Stewart
Scraped judge: Sarah Hawkins Warren
Scraped judge: Sarah Hennesy
Scraped judge: Sarah Keeton Campbell
Scraped judge: Scott L. Kafker
Scraped judge: Scott P. Myren
Scraped judge: Scott Rowland
Scraped judge: Scott Walker
Scraped judge: Serge Georges, Jr.
Scraped judge: Sharon L. Kennedy
Scraped judge: Shawn A. Womack
Scraped judge: Shawn Ellen LaGrua
Scraped judge: Sheryl Gordon McCloud
Scraped judge: Shirley M. Watts
Scraped judge: Shirley Troutman
Scraped judge: Stephanie F. Stacy
Scraped judge: Stephen Bushong
Scraped judge: Stephen R.
McCullough
Scraped judge: Steven A. González
Scraped judge: Steven B. Gould
Scraped judge: Steven D. Ecker
Scraped judge: Steven R. Jensen
Scraped judge: Stuart Rabner
Scraped judge: Susan Christensen
Scraped judge: Susan Crawford
Scraped judge: Susan M. Carney
Scraped judge: Tamara Barringer
Scraped judge: Teresa M. Chafin
Scraped judge: Theodora Gaitas
Scraped judge: Thomas D. Waterman
Scraped judge: Thomas Ewing
Scraped judge: Thomas Mann
Scraped judge: Todd W. Eddins
Scraped judge: Tommy Bryan
Scraped judge: Travis Jett
Scraped judge: Trey Allen
Scraped judge: Valerie Stanfill
Scraped judge: Verda M. Colvin
Scraped judge: Vijay Shanker
Scraped judge: Vladimir Devens
Scraped judge: W. Brent Powell
Scraped judge: Wayne Douglas
Scraped judge: Wesley G. Russell Jr.
Scraped judge: Will Parker
Scraped judge: William B. Cassel
Scraped judge: William B. Sellers
Scraped judge: William G. Montgomery
Scraped judge: William H. Bright, Jr.
Scraped judge: William J. Musseman, Jr.
Scraped judge: William P. Robinson III
Scraped judge: William R. Wooton
Scraped judge: William W. Hood, III
Scraped judge: Zel M. Fischer

In [ ]:
# Cases with no opinion documents
case_df[~case_df["opinion_link"].str.contains("statecourt", na=False)]

,docket_no,title,state,date,type,pending,opinion_link
0,25-0139,Kalarchik v. State,Montana,"April 14, 2026",Civil Rights,False,https://statecourtreport.org/sites/default/fil...
15,OP 25-0858,Kendrick v. Knudsen,Montana,"February 27, 2026",Voting Rights and Elections,False,https://statecourtreport.org/sites/default/fil...
22,PR 23-0496,In the Matter of Austin Miles Knudsen,Montana,"December 31, 2025",Government Structure,False,https://statecourtreport.org/sites/default/fil...
32,DA 24-0039,Montanans Against Irresponsible Densification ...,Montana,"March 17, 2026",Civil Rights,False,https://statecourtreport.org/sites/default/fil...
39,DA 24-0250,State v. Alford,Montana,"August 5, 2025",Criminal Law,False,https://statecourtreport.org/sites/default/fil...
48,OP 25-0729,Montanans for Nonpartisan Courts v. Knudsen,Montana,"November 18, 2025",Voting Rights and Elections,False,https://statecourtreport.org/sites/default/fil...
50,DA 23-0462,City of Kalispell v. Doman,Montana,"February 10, 2026",Speech and Religion,False,https://statecourtreport.org/sites/default/fil...
82,DA 23-0229,State v. Herzog,Montana,"June 17, 2025",Criminal Law,False,https://statecourtreport.org/sites/default/fil...
99,DA 24-0501,Netzer v. State,Montana,"November 4, 2025",Civil Rights,False,https://statecourtreport.org/sites/default/fil...
160,DA 23-0648,Montana Environmental Information Center v. Of...,Montana,"May 29, 2025",Economic and Labor Rights,False,https://statecourtreport.org/sites/default/fil...
225,DA 23-0225,Montana Environmental Information Center & Sie...,Montana,"January 3, 2025",Environment,False,https://statecourtreport.org/sites/default/fil...
226,DA 23-0268,Montana Trout Unlimited v. Montana Department ...,Montana,"January 2, 2025",Environment,False,https://statecourtreport.org/sites/default/fil...
240,DA 24-0324,Cottonwood Environmental Law Center v. State,Montana,"December 18, 2024",Government Structure,False,https://statecourtreport.org/sites/default/fil...
249,DA 23-0555,O’Neil v. Gianforte,Montana,"January 2, 2025",Government Structure,False,https://statecourtreport.org/sites/default/fil...
255,DA 24-0147,Planned Parenthood of Montana v. State (Planne...,Montana,"June 9, 2025",Reproductive Rights,False,https://statecourtreport.org/sites/default/fil...
259,DA 23-0572,Cross v. State,Montana,"December 11, 2024",Civil Rights,False,https://statecourtreport.org/sites/default/fil...
303,DA 23-0287,Planned Parenthood of Montana v. State (Planne...,Montana,"October 9, 2024",Reproductive Rights,False,https://statecourtreport.org/sites/default/fil...
304,DA 23-0288,Planned Parenthood of Montana v. State (Planne...,Montana,"October 9, 2024",Reproductive Rights,False,https://statecourtreport.org/sites/default/fil...
311,DA 23-0382,Acorn International v. State,Montana,"August 20, 2024",Election 2024,False,https://statecourtreport.org/sites/default/fil...
324,DA 23-0136,State v. Case,Montana,"August 6, 2024",Criminal Law,False,https://statecourtreport.org/sites/default/fil...
338,DA 23-0272,Planned Parenthood of Montana v. State of Mont...,Montana,"August 14, 2024",Reproductive Rights,False,https://statecourtreport.org/sites/default/fil...
356,DA 23-0575,Held v. Montana,Montana,"December 18, 2024",Environment,False,https://statecourtreport.org/sites/default/fil...
394,OP 23-0634,Montanans for Election Reform Action Fund v. K...,Montana,"November 22, 2023",Election 2024,False,https://statecourtreport.org/sites/default/fil...
401,DA 22-0639,Forward Montana v. State,Montana,"April 9, 2024",Government Structure,False,https://statecourtreport.org/sites/default/fil...
412,DA 22-0586,Barrett v. Montana,Montana,"April 26, 2024",Education,False,https://statecourtreport.org/sites/default/fil...
424,DA 21-0413,State v. Gibbons,Montana,"March 20, 2024",Criminal Law,False,https://statecourtreport.org/sites/default/fil...
438,OP 24-0182,Montanans Securing Reproductive Rights v. Knudsen,Montana,"April 1, 2024",Reproductive Rights,False,https://statecourtreport.org/sites/default/fil...
460,DA 22-0639,Forward Montana v. State,Montana,"January 31, 2024",Government Structure,False,https://statecourtreport.org/sites/default/fil...
501,"DA 22-0172, DA 22-0667",Montana Democratic Party v. Jacobsen,Montana,"March 27, 2024",Election 2024,False,https://statecourtreport.org/sites/default/fil...
541,OP 23-0331,Monforton v. Knudsen,Montana,"September 26, 2023",Voting Rights and Elections,False,https://statecourtreport.org/sites/default/fil...
547,"DA 21-0533, DA 23-0046",Stand Up Montana v. Missoula County Public Sch...,Montana,"December 12, 2023",Education,False,https://statecourtreport.org/sites/default/fil...
559,DA 20-0197,State v. Hinman,Montana,"June 14, 2023",Criminal Law,False,https://statecourtreport.org/sites/default/fil...
623,DA 20-0461,State v. Noli,Montana,"May 16, 2023",Criminal Law,False,https://statecourtreport.org/sites/default/fil...
626,DA 22-0207,Weems v. State,Montana,"May 12, 2023",Reproductive Rights,False,https://statecourtreport.org/sites/default/fil...
690,OP 22-0621,A.J.B. v. Montana Eighteenth Judicial District...,Montana,"January 17, 2023",Civil Rights,False,https://statecourtreport.org/sites/default/fil...
694,DA 20-0562,State v. Staudenmayer,Montana,"January 10, 2023",Criminal Law,False,https://statecourtreport.org/sites/default/fil...
724,DA 20-0603,State v. Larson,Montana,"November 9, 2022",Criminal Law,False,https://statecourtreport.org/sites/default/fil...
744,DA 20-0330,State v. Mefford,Montana,"September 27, 2022",Criminal Law,False,https://statecourtreport.org/sites/default/fil...
766,DA 22-0229,McDonald v. Jacobsen,Montana,"August 12, 2022",Voting Rights and Elections,False,https://statecourtreport.org/sites/default/fil...
830,OP 22-0219,Meyer v. Knudsen,Montana,"June 2, 2022",Voting Rights and Elections,False,https://statecourtreport.org/sites/default/fil...
833,DA 20-0379,State v. Wellknown,Montana,"May 24, 2022",Civil Rights,False,https://statecourtreport.org/sites/default/fil...
870,DA 21-0314,Advocates for School Trust Lands v. State,Montana,"March 8, 2022",Government Structure,False,https://statecourtreport.org/sites/default/fil...
886,DA 21-0392,Associated Press v. Usher,Montana,"February 8, 2022",Government Structure,False,https://statecourtreport.org/sites/default/fil...
902,DA 19-0070,State v. Peoples,Montana,"January 11, 2022",Criminal Law,False,https://statecourtreport.org/sites/default/fil...
913,DA 20-0382,State v. Smith,Montana,"December 28, 2021",Criminal Law,False,https://statecourtreport.org/sites/default/fil...
987,OP 21-0173,McLaughlin v. Montana State Legislature,Montana,"July 14, 2021",Government Structure,False,https://statecourtreport.org/sites/default/fil...
999,DA 19-0731,State v. Staker,Montana,"June 22, 2021",Criminal Law,False,https://statecourtreport.org/sites/default/fil...
1012,OP 21-0125,Brown v. Gianforte,Montana,"June 10, 2021",Government Structure,False,https://statecourtreport.org/sites/default/fil...
1015,DA 18-0187,State v. Smith,Montana,"June 8, 2021",Criminal Law,False,https://statecourtreport.org/sites/default/fil...
1044,DA 18-0639,State v. Lamoureux,Montana,"April 20, 2021",Speech and Religion,False,https://statecourtreport.org/sites/default/fil...
1077,DA 19-0484,Clark Fork Coalition v. Montana Department of ...,Montana,"February 17, 2021",Environment,False,https://statecourtreport.org/sites/default/fil...
1095,19-0368,State v. Keefe,Montana,"January 8, 2021",Criminal Law,False,https://statecourtreport.org/sites/default/fil...

In [38]:
class Opinion(BaseModel):
    judge_name: str = Field(description="The full name of the judge giving an opinion.")
    opinion_summary: str = Field(
        description="An extremely brief description of the judge's opinion on the case."
    )


class Case(BaseModel):
    title: str = Field(description="The title of the case.")
    decision: str = Field(description="The final decision that was made for the case.")
    issue_debate: str = Field(description="The main issue being debated in the case.")
    judge_opinions: List[Opinion]

In [39]:
def read_opinion(pdf_link: str, model_id: str, client: genai.Client, prompt: str):
    resp = requests.get(pdf_link).content

    genai_resp = client.models.generate_content(
        model=model_id,
        contents=[types.Part.from_bytes(data=resp, mime_type="application/pdf"), prompt],
        config={
            "response_mime_type": "application/json",
            "response_json_schema": Case.model_json_schema(),
        },
    )

    return Case.model_validate_json(genai_resp.text)

In [ ]:
def analyze_state_cases(
    case_df: pd.DataFrame, judge_df: pd.DataFrame, prompt_start: str, client_info: dict
):
    prompt = prompt_start + "$DATAFRAME$" + judge_df.to_markdown(index=False)
    num_cases = len(case_df)
    model_id = client_info["model_id"]
    client = client_info["client"]

    file_dic = {}
    for i in range(num_cases):
        print(f"Querying case {i}")
        docket_no = case_df.iloc[i]["docket_no"].replace(" ", "-")
        state = case_df.iloc[i]["state"]
        date = str(datetime.strptime(case_df.iloc[i]["date"], "%B %d, %Y"))[:10].replace("-", "/")
        pdf_link = case_df.iloc[i]["opinion_link"]

        case_ref = "_".join([docket_no, state, date])

        opinion_resp = read_opinion(pdf_link, model_id, client, prompt)

        file_dic[case_ref] = {}
        file_dic[case_ref]["pdf_link"] = pdf_link
        file_dic[case_ref]["response"] = opinion_resp.model_dump()

    return file_dic

In [ ]:
def apply_model(case_df: pd.DataFrame, judge_df: pd.DataFrame, prompt_path: str):
    with open(prompt_path, "r") as prompt_file:
        prompt_start = prompt_file.read()

    load_dotenv(find_dotenv())

    gemini_key = os.getenv("GEMINI_API_KEY")
    client_info = {"model_id": "gemini-2.5-flash-lite", "client": genai.Client(api_key=gemini_key)}

    case_dic = analyze_state_cases(case_df, judge_df, prompt_start, client_info)

    return case_dic

In [ ]:
def state_opinion_table(case_dic: dict):
    opinion_table = {"case_id": [], "name": [], "opinion": []}

    for key in case_dic.keys():
        opinions = case_dic[key]["response"]
        num_opinions = len(opinions["judge_opinions"])

        for i in range(num_opinions):
            opinion_table["case_id"].append(key)
            judge_name = opinions["judge_opinions"][i]["judge_name"]
            opinion_table["name"].append(judge_name)
            opinion_summary = opinions["judge_opinions"][i]["opinion_summary"]
            opinion_table["opinion"].append(opinion_summary)

    return pd.DataFrame(opinion_table)

In [45]:
mon_cases = case_df[case_df["state"] == "Montana"].head(5)
mon_judges = judge_pd[judge_pd["state"] == "MT"]

mon_opinions = state_opinion_table(mon_cases, mon_judges, "prompt.txt")

Querying case 0
Querying case 1
Querying case 2
Querying case 3
Querying case 4

In [ ]:
def state_case_table(case_df: pd.DataFrame, case_dic: dict):
    case_table = {
        "case_id": [],
        "docket_no": [],
        "title": [],
        "state": [],
        "date": [],
        "type": [],
        "dispute_desc": [],
        "decision_outcome": [],
        "decision_status": [],
    }
    num_cases = len(case_df)

    for i in range(num_cases):
        docket_no = case_df.iloc[i]["docket_no"].replace(" ", "-")
        case_table["docket_no"].append(docket_no)
        state = case_df.iloc[i]["state"]
        case_table["state"].append(state)
        date = str(datetime.strptime(case_df.iloc[i]["date"], "%B %d, %Y"))[:10].replace("-", "/")
        case_table["date"].append(date)

        title = case_df.iloc[i]["title"]
        case_table["title"].append(title)
        type = case_df.iloc[i]["type"]
        case_table["type"].append(type)

        case_id = "_".join([docket_no, state, date])
        case_table["case_id"].append(case_id)

        response = case_dic[case_id]["response"]
        case_table["dispute_desc"].append(response["issue_debate"])
        case_table["decision_outcome"].append(response["decision"])

        status = case_df.iloc[i]["pending"]
        case_table["decision_status"].append(status)

    return pd.DataFrame(case_table)

In [ ]:
def produce_tables(case_df: pd.DataFrame, judge_df: pd.DataFrame, prompt_path: str):
    states = case_df["state"].sort_values().unique()

    opinions = []
    cases = []

    for state in states:
        state_cases = case_df[case_df["state"] == state]

        state_abbr = us.states.lookup(state).abbr
        state_judges = judge_df[judge_df["state"] == state_abbr]

        case_dic = apply_model(state_cases, state_judges, prompt_path)

        opinions.append(state_opinion_table(case_dic))
        cases.append(state_case_table(state_cases, case_dic))

    rd = {"opinion_table": pd.concat(opinions), "case_table": pd.concat(cases)}

    return rd

,case_id,docket_no,title,state,date,type,dispute_desc,decision_outcome,decision_status
0,"2025-O-00879_Louisiana_October-24,-2025",2025-O-00879,In re Judge Jennifer Medley,Louisiana,"October-24,-2025",Judicial Selection and Administration,The main issue debated is whether Judge Medley...,Judge Medley was suspended for thirty days wit...,False
1,"2024-KK-00737_Louisiana_May-9,-2025",2024-KK-00737,State v. Davieontray Breax,Louisiana,"May-9,-2025",Criminal Law,The issue is whether prosecutors may join capi...,"The indictment was quashed, and the matter was...",False
2,"2024-CA-00995,-2024-CA-00996_Louisiana_March-2...","2024-CA-00995,-2024-CA-00996","Fremin v. Boyd Racing, LLC",Louisiana,"March-21,-2025",Civil Rights,"The issue debated is whether Act 437, which le...",The court affirmed the district court's judgme...,False
3,"2024-CC-00899_Louisiana_March-21,-2025",2024-CC-00899,Welch v. United Medical Healthwest-New Orleans,Louisiana,"March-21,-2025",Voting Rights and Elections,The main issue debated is whether La. R.S. 29:...,The trial court's denial of Welch's motion to ...,False
4,"2024-CD-00359_Louisiana_October-25,-2024",2024-CD-00359,Fisher v. Harter,Louisiana,"October-25,-2024",Government Structure,"The main issue is whether La. R.S. 13:4163, wh...",The Court reversed the district court's denial...,False