In [4]:
from ingest_cases_opinions import produce_tables, case_df

In [8]:
test_df = case_df.sample(frac=1).reset_index(drop=True).head(5)
test_df

,docket_no,title,state,date,type,pending,opinion_link
0,21-2022,In re Petition for Emergency Remedy By Marylan...,Maryland,"March 29, 2023",Voting Rights and Elections,False,https://statecourtreport.org/sites/default/fil...
1,SC 20447,State v. Graham,Connecticut,"October 4, 2022",Criminal Law,False,https://statecourtreport.org/sites/default/fil...
2,"SC19-1250, SC19-1343",Emerson v. Hillsborough County,Florida,"February 25, 2021",Government Structure,False,https://statecourtreport.org/sites/default/fil...
3,2024-Ohio-4547,State ex rel. Citizens Not Politicians v. Ohio...,Ohio,"September 16, 2024",Voting Rights and Elections,False,https://statecourtreport.org/sites/default/fil...
4,2023-0156,State v. Carter,Ohio,"April 4, 2024",Criminal Law,False,https://statecourtreport.org/sites/default/fil...

In [11]:
test_output = produce_tables(test_df, model_id="gemini-3-flash-preview")

Querying case 0
Querying case 0
Querying case 0
Querying case 0
Querying case 1

In [13]:
tables, meta_data = test_output

In [15]:
tables["case"]

,case_id,docket_no,title,state,date,type,description,plaintiff_argument,defendant_argument,decision_outcome,...,reproductive_rights,democratic_norms,free_press,public_health,separation_church_state,voting_access,public_education,free_speech,privacy,worker_rights
0,SC-20447_Connecticut_2022/10/04,SC-20447,State v. Graham,Connecticut,2022/10/04,Criminal Law,Whether the trial court erred by admitting an ...,The state argued that the accomplice's stateme...,The defendant argued that the admitted stateme...,The Supreme Court of Connecticut affirmed the ...,...,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA
0,"SC19-1250,-SC19-1343_Florida_2021/02/25","SC19-1250,-SC19-1343",Emerson v. Hillsborough County,Florida,2021/02/25,Government Structure,Whether a voter-approved charter amendment for...,The amendment's spending mandates unconstituti...,The charter amendment is constitutional as it ...,"The court ruled with the plaintiffs, declaring...",...,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA
0,21-2022_Maryland_2023/03/29,21-2022,In re Petition for Emergency Remedy By Marylan...,Maryland,2023/03/29,Voting Rights and Elections,Whether the Maryland State Board of Elections ...,The State Board argued that the massive volume...,Daniel Cox argued that the emergency statute u...,The court affirmed the circuit court's order p...,...,NA,protected,NA,NA,NA,protected,NA,NA,NA,NA
0,2024-Ohio-4547_Ohio_2024/09/16,2024-Ohio-4547,State ex rel. Citizens Not Politicians v. Ohio...,Ohio,2024/09/16,Voting Rights and Elections,Whether the ballot language and ballot title a...,The relators argued that the ballot language u...,The respondents argued that the ballot languag...,The court granted a limited writ of mandamus o...,...,NA,protected,NA,NA,NA,NA,NA,NA,NA,NA
1,2023-0156_Ohio_2024/04/04,2023-0156,State v. Carter,Ohio,2024/04/04,Criminal Law,Whether a trial court's decision to allow a wi...,The State argued that the COVID-19 pandemic an...,The defendant argued that remote testimony vio...,"The court affirmed the defendant's conviction,...",...,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA